# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a516cf2760b4c90fb81d561acfe49c9c48c69a76f297d54b47b4ea4be397191f084a50c95862156d783fa2812f9646a2d6d4184ba86f251d53f7987ab7c17ce

test:
  secret_key_base: b46634df735991defefb8e1edbfd9c0f34534827f0511e052c4b1229e8b03bd7a9e8d3fd15dc73f6502dc607de8e30ae74ce2f32aef0b7954a245d94912006ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
